### ISSUE TITLE
More GTFS validation

### ISSUE THREAD

**Issue by tapioko** [tmfg/mmtis-national-access-point#1323]
Not sure if this repo is the right place for this feature request, but here goes:

API `https://finap.fi/ote/service-search?sub_types=schedule&response_format=json` returns JSON, where some items have field `gtfs-import-error`. It contains useful error messages like "Invalid interface package: Missing required files in gtfs zip file", so API users can skip GTFS files with that error field.

Would it be possible to extend that validation so that e.g. https://tvv.fra1.digitaloceanspaces.com/211.zip would not pass validation? That particular zip-file contains file `translations.txt`, which is missing required `table_name` field. Source: https://developers.google.com/transit/gtfs/reference#translationstxt

**Comment by esuomi** [comment]
Hi  @tapioko !

I know I'm several years late in reply, sorry for that, but on the off chance you see this, Fintraffic now has a new service for validating various feeds: https://www.fintraffic.fi/fi/fintraffic/validointi-ja-konvertointipalvelu ("VACO")

The equivalent functionality in FINAP is being transitioned to use this new VACO service in the background, and in fact has already been running validations and conversions over integration for the past few weeks or so.

I also understand that this is not really an answer to your question, but is more of a context of what's been done in related development efforts. The actual answer is maybe a bit less enthusiastic: As mentioned, FINAP's validation and conversion functionality is being replaced with this new VACO service, and as such modifications to the related logic in FINAP itself are not going to be implemented. However if you feel you have a need for improved validation, or are in general more interested about using VACO, don't hesitate to send an email to nap@fintraffic.fi and we'll continue from there.
